"""Recode every scored run in results/ideas_results.csv into the intervention-family taxonomy.

The unit of classification is the CONTRAST an experiment was run to test, not the properties
of the model it produced. A shipped member may be a bi-GRU with a dual objective and snapshot
averaging; the experiment that admitted it tested exactly one of those against a control.

  F1 signal        what information the predictor may see
  F2 mechanism     the map from covariates to forecast (function class)
  F3 target        what prediction problem is optimised (loss, target scale, factorisation)
  F4 exposure      which training examples are seen (augmentation, rollout regime)
  F5 estimation    how the same predictor is estimated from finite data (seeds, snapshots)
  F6 adaptation    a fitted correction applied to or around a finished forecast
  F7 combination   which trained predictors are kept and how they are pooled
  F8 uncertainty   the predictive interval rather than the point forecast
  P  protocol      procedures whose object is choosing or evaluating, not predicting
  X  compound      deliberately changed more than one stage; not clean single-family evidence

Every code below is assigned explicitly so the coding can be audited and re-run.
Usage: python3 family_ledger.py [--tex]
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ASSIGN = {
 "F1": """I16 I17 I17b S45 S46 S46b S47 S47b S60 S60b S60c S60d S61 S61b U1 U1b U1c
          E4 E4b E4c E4d F1 F1b F1c F1d F1e F2 F3 F4 I08 S41 T1
          FS0 FS1a FS1b FS1c FS1d FS1e FS2a FS2b FS2c FS2d FS2e""",
 "F2": """S21 S21b S22 S22b S22c S23 S23b S23c S23d S25 S26 S27 S28 S29 S29b S29c S29d S29e
          S30 S31 S32 S33 S34 S42 S43 S39 S39b I07 I12 E1 E2 E3 E5 B1 B2 B2b B3 K1 K1b
          D1 D2 D3 D4 D5 P1 P1b P1c P1d R8 R8b M2 I02 I03 I04 I14
          TS1 TS1b TS2 TS2b TS3 TS3b SX1 SX2 SX4""",
 "F3": """S24 S24b S44 S44b S50 S51 S62 S37 S54 A5 A11 A11x25 I09 I13 I06 H1 H2
          I05 I05b TS2c TS2d I11w S35w S39w X9w SX3""",
 "F4": """I11 S35 S36 S40 S63 S63b S63c A2 A2b A7 A7b A8 A9 A9b A9c A9d A10 A10b A10c A10d
          P3 P3b P4 M1 M1b M1c M1d""",
 "F5": """A1 A1x25 A3 A3x25 I20 S38 X1 X2 X3 X4 X5 X6 X7 X8 X9 X10 X11 Y1 Y2 Y3 Y4 Y5 Y6 Y7""",
 "F6": """A4 A4b M3 M3b M3c S64""",
 "F7": """N1b N1c N2 N2b""",
 "F8": """I10""",
 "P":  """RT1 RT2 RT3 RT4""",
 "X":  """I01 I15 I18 S52 S53""",
}
NAME = {"F1": "signal", "F2": "mechanism", "F3": "target", "F4": "exposure",
        "F5": "estimation", "F6": "adaptation", "F7": "combination",
        "F8": "uncertainty", "P": "protocol", "X": "compound"}
# Families whose decisive evidence is a paired contrast against the shipped blend rather than a
# solo out-of-fold score. Counts are recorded in the report text, not in this table.
OFF_LEDGER = {"F6": "12 further post-hoc corrections tested against the blend (all rejected)",
              "F7": "14 further combination contrasts (weights, subset, add/drop, ampshape)",
              "F8": "2 conformal variants (coverage, not RMSE)"}


def code_to_family():
    m = {}
    for fam, s in ASSIGN.items():
        for c in s.split():
            assert c not in m, f"{c} assigned twice"
            m[c] = fam
    return m


def main():
    d = pd.read_csv(Path(__file__).parent / "results" / "ideas_results.csv")
    d["code"] = d.idea.str.split().str[0]
    m = code_to_family()
    d["fam"] = d.code.map(m)
    missing = sorted(set(d.code[d.fam.isna()]))
    if missing:
        print(f"UNASSIGNED ({len(missing)}): {missing}")
    d = d.dropna(subset=["fam"])
    g = d.groupby("fam").agg(n=("rmse_mean", "size"), best=("rmse_mean", "min"),
                             median=("rmse_mean", "median"))
    g = g.reindex([k for k in NAME if k in g.index])
    print(f"{'code':5} {'family':13} {'runs':>5} {'best':>9} {'median':>9}")
    for k, r in g.iterrows():
        print(f"  {k:4} {NAME[k]:13} {int(r.n):5d} {r.best:9.5f} {r['median']:9.5f}")
    print(f"  {'':4} {'TOTAL':13} {int(g.n.sum()):5d}   ({len(d)} of {len(pd.read_csv(Path(__file__).parent/'results'/'ideas_results.csv'))} scored runs assigned)")
    if "--tex" in sys.argv:
        print("\n% --- generated by family_ledger.py; do not hand-edit")
        for k, r in g.iterrows():
            print(f"{k} {NAME[k]} & {int(r.n)} & {r.best:.5f} \\\\")


if __name__ == "__main__":
    main()
